default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - --fix=lf
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff-check
        args:
          - --fix
      - id: ruff-format
  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: poetry run pyright
        language: node
        require_serial: true
        pass_filenames: false
        additional_dependencies: ["pyright@1.1.405"]
