name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: pipx install poetry
      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "poetry"
      - run: poetry install
      - uses: pre-commit/action@v3.0.1
